spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/honeypot_db
    username: postgres
    password: 9134246c  # ← 너가 설정한 비밀번호

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080